---

# Install httpd
- name: Install items needed for HTTPD
  yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - "httpd"
    - "mod_ssl"
  notify:
    - httpdHandler

# start httpd first
- name: Ensure httpd is started for file generation
  service:
    name: httpd
    state: started

# Check if httpd.conf exists
- name: Check file httpd.conf
  stat:
    path: "{{ apacheConfLocationDest }}"
  register: apacheConfLocationStatus

# Check if ssl.conf exists
- name: Check file ssl.conf
  stat:
    path: "{{ apacheConfLocationSSLDest }}"
  register: apacheConfLocationSSLStatus

# place custom apache conf
- name: Place custom httpd.conf
  template:
    dest: "{{ apacheConfLocationDest }}"
    src: "{{ apacheConfLocationSrc }}"
    mode: 0644
  when: apacheConfLocationStatus.stat.exists

# place custom ssl conf
- name: Place custom ssl.conf
  template:
    dest: "{{ apacheConfLocationSSLDest }}"
    src: "{{ apacheConfLocationSSLSrc }}"
    mode: 0644
  when: apacheConfLocationSSLStatus.stat.exists
