---

# Install nginx
- name: Install items needed for NGINX
  yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - "nginx"
    - "mod_ssl"
  notify:
    - nginxHandler

# start nginx first
- name: Ensure nginx is started for file generation
  service:
    name: nginx
    state: started

# Check if nginx config exists
- name: Check file nginx.conf
  stat:
    path: "{{ nginxConfLocation }}"
  register: nginxConfLocationStatus

# place custom nginx conf
- name: Place custom nginx.conf
  template:
    dest: "{{ nginxConfLocation }}"
    src: "{{ role_path }}/templates/nginx.conf.j2"
  when: nginxConfLocationStatus.stat.exists
