---

# Install nginx
- name: Install items needed for NGINX
  yum:
    name: "{{ item }}"
    state: present
    update_cache: true
  loop:
    - "nginx"
  notify:
    - nginxHandler

# start nginx first
- name: Ensure nginx is started for file generation
  service:
    name: nginx
    state: started

# Check if nginx config exists
- name: Check file nginx.conf
  stat:
    path: "{{ nginxConfLocationDest }}"
  register: nginxConfLocationStatus

# place custom nginx conf
- name: Place custom nginx.conf
  template:
    dest: "{{ nginxConfLocationDest }}"
    src: "{{ nginxConfLocationSrc }}"
    mode: 0644
  when: nginxConfLocationStatus.stat.exists
