---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/default/yaml-lint.yml
platforms:
  - name: instance
    image: "docker.pkg.github.com/ggiinnoo/docker-ansible/${DOCKER_IMAGE:-centos7}:latest"
    registry:
      url: docker.pkg.github.com
      credentials:
        username: ${DOCKER_USERNAME:-""}
        password: ${DOCKER_PASSWORD:-""}
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  log: true
  lint:
    name: ansible-lint
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
