---
name: Ansible role webserver

on:
  push:
    branches:
     -  'release/**'

jobs:
  build:
    name: Build for centos
    runs-on: ubuntu-latest
    strategy:
      matrix:
        centos: ['centos7']
        service: ['httpd'. 'nginx']
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: ansible-role-webserver
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install yamllint molecule[docker] docker ansible-lint yamllint
      - name: run Molecule
        env:
          DOCKER_IMAGE: ${{ matrix.centos }}
          DOCKER_SERVICE: ${{ matrix.service }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          cd ansible-role-webserver
          molecule test
